### ISSUE TITLE
soar doesn't respect `bin_path` config variable.

### ISSUE THREAD

**Issue by KotUW** [pkgforge/soar#25]
My config file is

```toml
default_profile = "default"
bin_path = "~/.local/bin"

[[repositories]]
name = "bincache"
url = "https://meta.pkgforge.dev/bincache/x86_64-Linux.sdb.zstd"
desktop_integration = false
pubkey = "https://meta.pkgforge.dev/bincache/minisign.pub"
signature_verification = true
sync_interval = "3h"

[[repositories]]
name = "pkgcache"
url = "https://meta.pkgforge.dev/pkgcache/x86_64-Linux.sdb.zstd"
desktop_integration = true
pubkey = "https://meta.pkgforge.dev/pkgcache/minisign.pub"
signature_verification = true
sync_interval = "3h"

[profile.default]
root_path = "/home/eve/.local/share/soar"
```
And `soar env` returs
```
[NOTE]: These values are not configurable via environment variables. They are derived from the config file or defaults.
SOAR_CONFIG=/home/eve/.config/soar/config.toml
SOAR_BIN=/home/eve/.local/share/soar/bin
SOAR_DB=/home/eve/.local/share/soar/db
SOAR_CACHE=/home/eve/.local/share/soar/cache
SOAR_PACKAGE=/home/eve/.local/share/soar/packages
SOAR_REPOSITORIES=/home/eve/.local/share/soar/repos
```

Expected `SOAR_BIN` to point to `.local/bin/`. Do I have to reload the config?
